# Run in an isolated binary directory: Blitzcrank writes _enum.dat/_temp.index.
foreach(required DATASET CONFIG LEGACY_EXE RUST_EXE VERIFY_EXE WORK_DIR)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
file(MAKE_DIRECTORY "${WORK_DIR}/legacy" "${WORK_DIR}/rust")
file(STRINGS "${DATASET}" rows LIMIT_COUNT 20000)
list(LENGTH rows count)
if(count LESS 100)
    message(FATAL_ERROR "Expected real Census data, not a Git LFS pointer")
endif()
string(REPLACE ";" "\n" rows "${rows}")
file(WRITE "${WORK_DIR}/input.csv" "${rows}\n")
file(COPY_FILE "${CONFIG}" "${WORK_DIR}/input.config")
foreach(block 1 20000)
    foreach(backend legacy rust)
        if(backend STREQUAL "legacy")
            set(program "${LEGACY_EXE}")
        else()
            set(program "${RUST_EXE}")
        endif()
        execute_process(COMMAND "${program}" -c ../input.csv payload.bin ../input.config 0 1 ${block}
            WORKING_DIRECTORY "${WORK_DIR}/${backend}" RESULT_VARIABLE status
            OUTPUT_FILE "${WORK_DIR}/${backend}/encode-${block}.log" ERROR_VARIABLE errors)
        if(NOT status EQUAL 0)
            message(FATAL_ERROR "${backend} encode failed: ${status}: ${errors}")
        endif()
        execute_process(COMMAND "${program}" -d payload.bin restored.csv ../input.config 0 ${block}
            WORKING_DIRECTORY "${WORK_DIR}/${backend}" RESULT_VARIABLE status
            OUTPUT_FILE "${WORK_DIR}/${backend}/decode-${block}.log" ERROR_VARIABLE errors)
        if(NOT status EQUAL 0)
            message(FATAL_ERROR "${backend} decode failed: ${status}: ${errors}")
        endif()
        file(SHA256 "${WORK_DIR}/input.csv" expected)
        file(SHA256 "${WORK_DIR}/${backend}/restored.csv" actual)
        if(NOT expected STREQUAL actual)
            message(FATAL_ERROR "${backend} record reconstruction mismatch")
        endif()
        execute_process(COMMAND "${VERIFY_EXE}" ${block}
            WORKING_DIRECTORY "${WORK_DIR}/${backend}" RESULT_VARIABLE status
            OUTPUT_FILE "${WORK_DIR}/${backend}/seeks-${block}.log" ERROR_VARIABLE errors)
        if(NOT status EQUAL 0)
            message(FATAL_ERROR "${backend} record seek failed: ${status}: ${errors}")
        endif()
    endforeach()
    foreach(file payload.bin _enum.dat _temp.index)
        file(SHA256 "${WORK_DIR}/legacy/${file}" legacy_hash)
        file(SHA256 "${WORK_DIR}/rust/${file}" rust_hash)
        if(NOT legacy_hash STREQUAL rust_hash)
            message(FATAL_ERROR "Block ${block}: ${file} is not bit-compatible")
        endif()
    endforeach()
    message(STATUS "${count} Census rows, threshold ${block}: payload/model/index identical; reconstruction and shuffled seeks pass")
endforeach()
